name: Deploy Website in Docker

on:
  push:
    branches:
      - main

jobs:
  create_docker_container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t my-website .

  install_dependencies:
    runs-on: ubuntu-latest
    needs: create_docker_container
    steps:
      - name: Run Docker container
        run: |
          docker run -d --name website-container -p 80:80 my-website

  expose_code:
    runs-on: ubuntu-latest
    needs: install_dependencies
    steps:
      - name: Expose code and get public IP
        run: |
          PUBLIC_IP=$(curl -s ifconfig.me)
          echo "Public IP Address: $PUBLIC_IP"

  deploy_to_browser:
    runs-on: ubuntu-latest
    needs: expose_code
    steps:
      - name: Display the public IP address
        run: |
          PUBLIC_IP=$(curl -s ifconfig.me)
          echo "Website deployed at: http://$PUBLIC_IP"
